name: run-textlint
on: 
  pull_request_target:
    types: [ opened, synchronize ] # PR作成または作業ブランチの同期
    paths: [ '**/*.md' ] # 全てのmarkdownファイル
jobs:
  run-textlint:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install Reviewdog
        uses: reviewdog/action-setup@v1

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install npm
        run: npm install
      
      - name: Execute textlint
        run: npx textlint **/*.md >> ./.textlint.log
      
      - name: Run Reviewdog
        if: ${{ failure() }} # 校正内容をPRにコメントする
        run: gh pr comment --body-file ./.textlint.log "${URL}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          URL: ${{ github.event.pull_request.html_url }}