name: run-textlint
on: 
  pull_request_target:
    types: [ opened, synchronize ] # PR作成または作業ブランチの同期
    paths: [ '**/*.md' ] # 全てのmarkdownファイル
  push:
    branches:
      - "**"
jobs:
  run-textlint:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npx textlint **/*.md >> ./.textlint.log
      - if: ${{ failure() }} # 校正内容をPRにコメントする
        run: gh pr comment --body-file ./.textlint.log "${URL}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          URL: ${{ github.event.pull_request.html_url }}